Specific Exception Handling
t0xic0der/wisdom-cli pull request #11
Opened 2020-10-09 06:17 UTC by divyagupta-98

2020-10-09 12:40 UTC, t0xic0der requested changes
Hi @divyagupta-98, as you are dealing with specifically HTTPTimeoutError - please restrict the PR changes to that only.

2020-10-09 12:49 UTC, t0xic0der requested changes
Please refrain from storing the exception in a variable.

2020-10-09 12:56 UTC, t0xic0der commented
Also, could you please make the commit message for 4410050 a bit more descriptive?

2020-10-09 13:30 UTC, divyagupta-98 commented
@t0xic0der Done with the changes.

2020-10-14 13:13 UTC, t0xic0der commented on main.py
> +                click.echo(click.style("CAVEAT > ", fg="red", bold=True) + "Timeout occured while processing the query.")
The exception-catching keyword here is misspelled. Please correct it.

2020-10-20 05:03 UTC, t0xic0der approved these changes
Looks good to me. Merging.

2020-10-20 05:06 UTC, merged